# Generated by Django 5.2.7 on 2025-10-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', through='articles.Scope', to='articles.tag', verbose_name='Тематики'),
        ),
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['article', 'is_main'], name='articles_sc_article_b53948_idx'),
        ),
    ]
