# Generated by Django 5.2.7 on 2025-10-21 10:07

from django.db import migrations

def copy_fk_to_m2m(apps, schema_editor):
    Student = apps.get_model('school', 'Student')
    # У модели в историческом состоянии есть и FK, и M2M.
    for s in Student.objects.all():
        if getattr(s, 'teacher_id', None):
            s.teachers.add(s.teacher_id)

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_teachers'),  # подставить свою предыдущую миграцию
    ]

    operations = [
        migrations.RunPython(copy_fk_to_m2m, migrations.RunPython.noop),
    ]
