# Generated by Django 5.2.7 on 2025-10-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_copy_fk_to_m2m'),
    ]

    operations = [
    ]
